apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
namespace: hawtio-dev
images:
- name: quay.io/phantomjinx/camel-github
  newName: quay.io/phantomjinx/camel-github
  newTag: 1.0.0-20231011_203947
